### ISSUE TITLE
no

### ISSUE THREAD

**Issue by thaanirs** [HarashnabinRoy/HarashnabinRoy#2]
no

_Originally posted by @HarashnabinRoy in https://github.com/HarashnabinRoy/HarashnabinRoy/pull/1#pullrequestreview-978156039_

why no
?

**Comment by HarashnabinRoy** [comment]
coz u cringe

**Comment by thaanirs** [comment]
watashiva chigamasu cringe

**Comment by HarashnabinRoy** [comment]
💋💋
